### ISSUE TITLE
controlsystems plugins not installed by caQtDM_Install

### ISSUE THREAD

**Issue by prjemian** [caqtdm/caqtdm#13]

**Comment by prjemian** [comment]
just confirmed with a fresh `git clone` that this is still a problem

solved it locally from the command line:

    pushd caqtdm/caQtDM_Binaries/
    tar cf - controlsystems/ | (cd $QTDM_LIBINSTALL && tar xf -)

**Comment by prjemian** [comment]
looks like cf94d5c is still the fix for this

**Comment by HelgeBrands** [comment]
Anton should look into this!

**Comment by AntonMezger** [comment]
install modified; should do it now
