### ISSUE TITLE
Qt panels do not connect to a softIOC

### ISSUE THREAD

**Issue by wkoprek** [caqtdm/caqtdm#17]
I have a softIOC called MTEST-PC-DIAG10 running on fin129-softioc (129.129.130.25). The EPICS_CA_ADDR_LIST on finlc is set to 129.129.130.255 129.129.131.255 129.129.137.255. I can access the records using caget but not from qt panels. My qt panels cannot connect to the PVs from finlc, but it works when I start the panels directly on fin129-softioc. Any idea where is the problem?

**Comment by HelgeBrands** [comment]
This is an EPICS /network problem and not an caqtdm problem. Ask your Controls contact they should help you.

Best regards
      Helge
