### ISSUE TITLE
Minimizing main message Window minimizes all UI windows

### ISSUE THREAD

**Issue by newville** [caqtdm/caqtdm#18]
Using 4.0.2 on Windows 7, minimizing the main message window or starting up with the -noMsg option minimizes not only the main message window but also all the displayed UI windows.  

Individual UI windows can be minimized without affecting other windows, but they do not minimize to the system tray as might be expected for other multi-window apps, but to a minimized form on the main window.

I did not dig very far into the code.  Is this expected behavior for Qt apps that minimizing the main app window also minimizes all children?  Is it something that can be altered easily to have this minimize separately from the children?

**Comment by HelgeBrands** [comment]
Yes you are completely right. This is a known bug. I have to figure out what is the best way, for this feature under windows.
