### ISSUE TITLE
build fails when source from .tar.gz file

### ISSUE THREAD

**Issue by prjemian** [caqtdm/caqtdm#19]
Download release 4.1.5 as

```
wget https://github.com/caqtdm/caqtdm/archive/V4.1.5.tar.gz
```

and proceeded to build on APS file system (lots of NFS cross-mounts).
Received lots of comments that `GIT_DISCOVERY_ACROSS_FILESYSTEM` was not defined.
This is unexpected as not git repository information is available in the .tar.gz file.

Git commands are being used to set the version string, including git repository information.

Here was my fix (removes calls to command line git):
* commented out lines 3-9 in `caQtDM_Viewer/qtdefs.pri`

A better fix would be to only use git commands in `qtdefs.pri` if git repository information is available.

**Comment by HelgeBrands** [comment]
thanks for this, we completely miss this THANKS!
