### ISSUE TITLE
Calling assistant with collectionfile

### ISSUE THREAD

**Issue by HelgeBrands** [caqtdm/caqtdm#2]
Example at : 
http://doc.qt.io/qt-5/qtassistant-simpletextviewer-example.html

Controlling Qt Assistant via the Assistant Class

We have to check where and how the installation should look, so that all platforms can find it

**Comment by AntonMezger** [comment]
To get the assistant to work with caQtDM manual, the following command has to be done (only once)

assistant -register path/caQtDM.qch
