### ISSUE TITLE
backspace key not recognized in VNC session

### ISSUE THREAD

**Issue by prjemian** [caqtdm/caqtdm#22]
We are having a little problem with caQtDM.  Has anyone has experienced this?  When using VNC to a beamline PC called MBE (Windows PC), the back space key is unresponsive in caQtDM.  We can use the back space function in all of the other applications. We can use the back space key in caQtDM on MBE when sitting in front on the PC.  We have also tested VNC to another windows PC called PIT (Windows PC) and everything works. We checked Real VNC and the setting are the same. Any Ideas?

**Comment by prjemian** [comment]
additional observation:

The original email to us mentioned TightVNC as well as RealVNC.  It is not certain which VNC client/server is running on which Windows computer.

A quick google search shows that there are open bugs in TightVNC related to backspace and escape keys:

1. https://superuser.com/questions/927785/esc-and-backspace-not-working-in-virtualbox-on-windows-host-via-vnc

2. https://sourceforge.net/p/vnc-tight/bugs/1239/

3. https://sourceforge.net/p/vnc-tight/bugs/1256/

The workaround seems to be to install the 32-bit version of TightVNC (or use a different VNC program).

-----------

We'll leave this issue open for additional comments or to report how the problem was resolved.

**Comment by AntonMezger** [comment]
Hi,

I guess you are using the key in catextentry widget to delete?

We will try after the holidays of h.brands, while we have to setup something.

Best regards

Anton

Envoyé de mon iPhone

Le 18 juil. 2017 à 17:30, Pete R Jemian <notifications@github.com<mailto:notifications@github.com>> a écrit :


We are having a little problem with caQtDM. Has anyone has experienced this? When using VNC to a beamline PC called MBE (Windows PC), the back space key is unresponsive in caQtDM. We can use the back space function in all of the other applications. We can use the back space key in caQtDM on MBE when sitting in front on the PC. We have also tested VNC to another windows PC called PIT (Windows PC) and everything works. We checked Real VNC and the setting are the same. Any Ideas?

**Comment by prjemian** [comment]
@AntonMezger : thanks, we are suspecting the problem is not with caQtDM but rather with the choice of VNC software on Windows.  This issue documents the problem so Google can find it if someone searches in the future.  We'll check to see if this involves only the `caTextEntry` widget or also `caLineEdit`.

**Comment by prjemian** [comment]
update:  TightVNC was originally  install but then we installed RealVNC and it had the same problems,

**Comment by AntonMezger** [comment]
is this still an issue?
