### ISSUE TITLE
caRelatedDisplay font change in release 4.0.2

### ISSUE THREAD

**Issue by timmmooney** [caqtdm/caqtdm#23]
Since the commit of Oct 14, 2015 to carowcolmenu.cpp ("knob border size now 3px and outset in order to look more like a button") related display buttons have a smaller font.  Style sheets have no effect on this.  I agree that the buttons look more like buttons after this change, but I would prefer to opt out of it anyway, because users are complaining that they have trouble reading the text on related display buttons.  I could, of course, change the size of the buttons, but I have so many displays to edit that it would be quite a lot of work.

**Comment by AntonMezger** [comment]
I would suggest you change for your version the internal stylesheet in carowcolmenu. When you are satisfied we could implement a switch in order to keep the old behaviour.

**Comment by AntonMezger** [comment]
I modified carowcolmenu.cpp. it should be much better now. please try it

**Comment by timmmooney** [comment]
Awesome!  Thanks.
