### ISSUE TITLE
a macro string with embedded spaces is not parsed right

### ISSUE THREAD

**Issue by timmmooney** [caqtdm/caqtdm#25]
caQtDM -attach -macro "xx=04, yy=ID" Main_04ID.ui & fails.
caQtDM -attach -macro "xx=04,yy=ID" Main_04ID.ui & works

**Comment by AntonMezger** [comment]
I know, but playing with the macro parser now, could lead to other problems, for the time being we will keep it like that

**Comment by AntonMezger** [comment]
has ben fixed
