### ISSUE TITLE
ENH: allow user to disable caScriptButton checkbox

### ISSUE THREAD

**Issue by prjemian** [caqtdm/caqtdm#26]
The caScriptButton widget has a checkbox used to display a diagnostic screen for script execution.  The diagnostic screen is great when developing the script but we would like to disable it (or even remove it) for production use in most cases.

Can an enhancement feature be provided to disable this checkbox?
The feature could be implemented in any of several ways.  

* [ ] option to disable the checkbox in the widget properties from Qt Designer
* [ ] stylesheet property
* [ ] runtime command line option

Easiest might be to implement as an option to disable the checkbox in the widget properties.

**Comment by AntonMezger** [comment]
I will take a look next week at this

Best regards

Anton

Envoyé de mon iPhone

Le 13 sept. 2017 à 19:08, Pete R Jemian <notifications@github.com<mailto:notifications@github.com>> a écrit :


The caScriptButton widget has a checkbox used to display a diagnostic screen for script execution. The diagnostic screen is great when developing the script but we would like to disable it (or even remove it) for production use in most cases.

Can an enhancement feature be provided to disable this checkbox?
The feature could be implemented in any of several ways.

  *    option to disable the checkbox in the widget properties from Qt Designer
  *    stylesheet property
  *    runtime command line option

Easiest might be to implement as an option to disable the checkbox in the widget properties.

**Comment by AntonMezger** [comment]
A property has been created to disable the check button

**Comment by prjemian** [comment]
Thanks!
