### ISSUE TITLE
ENH: simplifying user documentation contributions

### ISSUE THREAD

**Issue by prjemian** [caqtdm/caqtdm#27]
It's hard to contribute to the caQtDM documentation now.  Some things are not documented (such as the scripting syntax used by the *caScriptButton* widget, the configuration of the *caCamera* widget, what is the difference between *caScriptButton* and *caShellCommand*) and other things can be updated.  For example, the page on [custom widgets](http://epics.web.psi.ch/software/caqtdm/caQtDM_Manual) has internal page links that refer to the same document by a different name (see the section: *caQtDM Custom Widgets*).  The internal links do not work because the `href` includes a hard-coded document name (should just start with `#`).

One documentation tool that has been helpful in the Python world has been [Sphinx](http://www.sphinx-doc.org/en/stable/).  Sphinx builds html and/or PDF documentation from source code comments and additional restructured text files.  It *might* be able to do this for C++ projects like caQtDM.

Markdown is another possibility, perhaps using [caQtDM's wiki](https://github.com/caqtdm/caqtdm/wiki).

Would it be possible to use the wiki, Sphinx, or some other documentation system to simplify user contributions?

**Comment by prjemian** [comment]
The server that provided the [documentation for caQtDM](http://epics.web.psi.ch/software/caqtdm/caQtDM_Manual) is not online at this time.

The Internet Archive Wayback Machine has some captures of the content.  The most recent capture shows the documentation in a [single HTML file](https://web.archive.org/web/20221004231152/http://epics.web.psi.ch/software/caqtdm/caQtDM_Manual), recorded on 2022-10-22.

I'll use that as a reference to start a branch with [Sphinx](https://www.sphinx-doc.org/)-style documentation.  I will attempt to use the content on https://caqtdm.github.io/ as the first page, adding a link to the additional content from the `caQtDM_Manual` page.

**Comment by prjemian** [comment]
Still needs to start with this page and content: https://caqtdm.github.io/

Might be a challenge...

**Comment by HelgeBrands** [comment]
I merged it into development, Thanks a lot! I can build it, but I need an idea to port it into the io page.
