### ISSUE TITLE
caPolyLine objects not visible when converted using adl2ui & Qt 4.8.5

### ISSUE THREAD

**Issue by kmpeters** [caqtdm/caqtdm#29]
When building caQtDM (bac201fc1c7634ccaad21301ae25c719db143cef) on RHEL 7.4 using the system version of Qt (qt-4.8.5-13.el7.x86_64), the resulting adl2ui binary fails to correctly set the xyPairs property of a caPolyLine in a converted ui file.

An adl file that can be used to reproduce the problem is attached: [ttt.adl.txt](https://github.com/caqtdm/caqtdm/files/1318571/ttt.adl.txt)

When adl2ui uses v4.8.5 of the Qt libraries (system-installed), the resulting ui file contains a caPolyLine with this property:
```
            <property name="xyPairs">
                <string>244,10;</string>
            </property>
```
When this ui file is executed by caQtDM, the caPolyLine object is not visible.

When adl2ui uses v4.8.6 of the Qt libraries (locally-built), the resulting ui file contains a caPolyLine with this property:
```
            <property name="xyPairs">
                <string>10,10;244,10;</string>
            </property>
```
When this ui file is executed by caQtDM, the caPolyLine object is visible.

If there is a simple way to workaround this problem in the adl2ui code, it would save users of enterprise (slow-moving) versions of linux a lot of effort.

**Comment by AntonMezger** [comment]
It seems to me, that there is a bug in qt4.8.5 and I do not think, we can do anything about it.
