### ISSUE TITLE
caCamera with BPP=2

### ISSUE THREAD

**Issue by timmmooney** [caqtdm/caqtdm#30]
I think there's a problem in caCamera::eventFilter:

            case 2: {   // monochrome 2 bpp  (Damir camera)
                uchar *ptr = (uchar*)  savedData;
                int index = ((int) Ynew * savedWidth * 2 + 2 * (int) Xnew);
                if((Xnew >=0) && (Ynew >=0)  &&  (Xnew < Xmax) && (Ynew < Ymax) && (index < savedSize)) {
                    if(thisColormap == grey) Zvalue=ptr[index];
                    else Zvalue=ptr[index] * 256 + ptr[index+1];

                } else {
                    validIntensity = false;
                }
            }
                break;
I think this code is actually doing only 1 byte per pixel.

**Comment by AntonMezger** [comment]
You are right, but I do not have a camera of this type any more. Therefore I did not change that code. If you have such a camera, please correct the code.

**Comment by AntonMezger** [comment]
Dear Tim,

did you fix this issu. if yes please send me your correction, so that we can close the issue.

best regards

Anton

**Comment by Engbretson** [comment]
The code in caCamera should probably *not* be using any of the quirks/requirements of any specific camera. m_code and m_bpp might more correctly match Area Detector variables DataType and ColorMode. The former has values of Int8, UInt8, Int16, UInt16, Int32, Uint32, Float32, and Float64. The latter - Mono, Bayer, RGB1, RBG2, RBG3, YUV444, YUV422, and YUV421.  The current code basically only matches the common image format of Mono UINT8. The other 2 cameras, using only 1 byte out of 16-bit image or only 12-bits of 16 is probably not a format that anyone can readily use, while implementing the full set of image types probably would still display these unique cameras.

**Comment by AntonMezger** [comment]
I have installed a softioc with the ADSim module in order to look into this beginning of next year.

**Comment by AntonMezger** [comment]
in development path, there is a new version that will treat images in a new way
