### ISSUE TITLE
Access security

### ISSUE THREAD

**Issue by timmmooney** [caqtdm/caqtdm#31]
caQtDM seems to responds to changes in access-security status only when a display is opened.

**Comment by AntonMezger** [comment]
I have been playing a bit with access security and it seems that what I tried updated the access security in caQtDM. However the cursor shape does not change its aspect when the cursor does not leave and reenter the widget it was on. Is that the problem you experienced ?

**Comment by timmmooney** [comment]
This is not the symptom that was reported to me.  Users don't see the cursor change when it leaves or reenters the widget.  Currently their workaround is to close and reopen the display.

**Comment by AntonMezger** [comment]
When I tested, I got a monitor for the device when the access security changed. But I test on my machine without a gateway. At your place is there a gateway involved. In that case I would have to investigate further.

**Comment by timmmooney** [comment]
Yes, there is a gateway in this case.


Tim Mooney (mooney@aps.anl.gov) (630)252-5417
Beamline Controls Group (www.aps.anl.gov)
Advanced Photon Source, Argonne National Lab

________________________________

**Comment by AntonMezger** [comment]
With a soft ioc on the same machine, I get a callback called for data when access security changes. I also get another callback called for the security access change. Not impossible that this last callback will update correctly the screen.

I join a file you could  replace to see if it works now in your case.

Best regards

**Comment by AntonMezger** [comment]
please reopen issu if this is still not fixed (but shoud be)
