### ISSUE TITLE
add date, time, file name to printed output

### ISSUE THREAD

**Issue by prjemian** [caqtdm/caqtdm#32]
Some beam lines regularly print settings using the `print()` command.  In MEDM, each print was accompanied by date, time, and file name.  Can these be added?  Like this?

```
yyyy-mm-dd      screen_name.ui         hh:mm:ss
 --------------------------------------------------
|                                                  |
|         some ui                                  |
|                                                  |
 --------------------------------------------------

```

**Comment by prjemian** [comment]
Is this the place?  `caQtDM_Lib/src/caqtdm_lib.h`, between lines 186-196?

**Comment by prjemian** [comment]
I'm not a C++ programmer.  Here is my first idea:

```
        if (printDialog->exec() == QDialog::Accepted) {

            QPainter painter(printer);
            double xscale = printer->pageRect().width()/double(this->width());
            double yscale = printer->pageRect().height()/double(this->height());
            double scale = qMin(xscale, yscale);

            painter.translate(printer->paperRect().x() + printer->pageRect().width()/2,
                              printer->paperRect().y() + printer->pageRect().height()/2);
            painter.scale(scale, scale);
            painter.translate(-width()/2, -height()/2);
            QPixmap pm = QPixmap::grabWidget(this);
            painter.drawPixmap(0, 0, pm);

	    // https://github.com/caqtdm/caqtdm/issues/32
	    // TODO: consider character height into printed page size
	    int w = printer->pageRect().width();
	    int h = 10;    // FIXME: wild guess
	    QDate qdate = QDate::currentDate()
	    QTime qtime = QTime::currentTime()
	    QString yyyymmdd = qdate.toString("yyyy-MM-dd");
	    QString hhmmss = qtime.toString("hh:mm:ss");
	    QString screen_name = this->fileName;
	    painter.drawText(QRect(0, 0, w, h), Qt::AlignLeft, yyyymmdd);
	    painter.drawText(QRect(0, 0, w, h), Qt::AlignCenter, screen_name);
	    painter.drawText(QRect(0, 0, w, h), Qt::AlignRight, hhmmss);
        }
```

**Comment by prjemian** [comment]
This compiles and shows the (modified) ISO8601 time stamp for *landscape* screen grabs (fills space horizontally).   How to get the .ui screen name?

```
        if (printDialog->exec() == QDialog::Accepted) {

            QPainter painter(printer);
            double xscale = printer->pageRect().width()/double(this->width());
            double yscale = printer->pageRect().height()/double(this->height());
            double scale = qMin(xscale, yscale);
            painter.translate(printer->paperRect().x() + printer->pageRect().width()/2,
                              printer->paperRect().y() + printer->pageRect().height()/2);
            painter.scale(scale, scale);
            painter.translate(-width()/2, -height()/2);
            QPixmap pm = QPixmap::grabWidget(this);
            painter.drawPixmap(0, 0, pm);

			// https://github.com/caqtdm/caqtdm/issues/32
			// TODO: consider character height into printed page size
			int w = printer->pageRect().width();
			int h = 12;    // 12-point font
			QString text = QDate::currentDate().toString("yyyy-MM-dd");
			text += " " + QTime::currentTime().toString("hh:mm:ss");
			// TODO: text += ", " + this->fileName;

			QFont qfont = painter.font();
			qfont.setPointSizeF(h/scale);
			painter.setFont(qfont);
			
			painter.drawText(QRect(0, -h, w, h), Qt::AlignLeft, text);
        }
```

Also, this won't look good for *portrait* screen grabs that fill space vertically.  Need to consider the vertical space taken by the new row of text.

**Comment by prjemian** [comment]
Also, should apply this to `printPS()`

**Comment by AntonMezger** [comment]
Hi,
I will check and implement your proposal tomorrow

Best regards
Anton

Envoyé de mon iPhone

Le 24 oct. 2017 à 00:37, Pete R Jemian <notifications@github.com<mailto:notifications@github.com>> a écrit :


I'm not a C++ programmer. Here is my first idea:

        if (printDialog->exec() == QDialog::Accepted) {

            QPainter painter(printer);
            double xscale = printer->pageRect().width()/double(this->width());
            double yscale = printer->pageRect().height()/double(this->height());
            double scale = qMin(xscale, yscale);

            painter.translate(printer->paperRect().x() + printer->pageRect().width()/2,
                              printer->paperRect().y() + printer->pageRect().height()/2);
            painter.scale(scale, scale);
            painter.translate(-width()/2, -height()/2);
            QPixmap pm = QPixmap::grabWidget(this);
            painter.drawPixmap(0, 0, pm);

            // https://github.com/caqtdm/caqtdm/issues/32
            // TODO: consider character height into printed page size
            int w = printer->pageRect().width();
            int h = 10;    // FIXME: wild guess
            QDate qdate = QDate::currentDate()
            QTime qtime = QTime::currentTime()
            QString yyyymmdd = qdate.toString("yyyy-MM-dd");
            QString hhmmss = qtime.toString("hh:mm:ss");
            QString screen_name = this->fileName;
            painter.drawText(QRect(0, 0, w, h), Qt::AlignLeft, yyyymmdd);
            painter.drawText(QRect(0, 0, w, h), Qt::AlignCenter, screen_name);
            painter.drawText(QRect(0, 0, w, h), Qt::AlignRight, hhmmss);
        }

**Comment by AntonMezger** [comment]
I implemented the date/time and  filename in the print function; you may try the file caQtDM_lib.h.

Best regards

Anton

**Comment by prjemian** [comment]
Thanks.  I'm looking at your commit 3327876 now and will try it later today.

**Comment by prjemian** [comment]
Those changes look good.  Closing issue now.  I may request an additional change to bring the date/time and short file name close to the printed image since the requester is used to printing, then cutting the figure out and pasting it in a paper notebook.
