### ISSUE TITLE
caFrame background not visible within QToolBox

### ISSUE THREAD

**Issue by keenanlang** [caqtdm/caqtdm#35]
A caFrame's background seems to become invisible when placed inside a QToolBox page.

### Steps to Replicate:

- Make a caFrame
- Set its backgroundMode to "Filled"
- Make a QToolBox
- Place the caFrame within the QToolBox

**Expected Result**: The caFrame's background remains the same as it was outside the QToolBox

**Actual Result**: The caFrame's background disappears, but any widgets within the caFrame remain.

**Comment by AntonMezger** [comment]
This is due to the propagation of the internal QToolbox stylesheet. However you may use a stylesheet yourself to prevent this behaviour, Ex: QFrame {\nbackground-color: red;}
set this to the page where your frame is setting.
