### ISSUE TITLE
caRelatedDisplay Font Property Ignored

### ISSUE THREAD

**Issue by keenanlang** [caqtdm/caqtdm#36]
The caRelatedDisplay Font property doesn't do anything when changed in Qt Designer. Stylesheets, however, are capable of successfully modifying the font.

### Steps to Replicate:

- Make a caRelatedDisplay
- Set stacking mode to Menu
- Set Label to "TEST"
- Set font family to anything
- Turn on Bold/Italic/Underline

**Expected Result**: Changing the font changes the display font of the label.

**Actual Result**: Nothing changes

**Comment by AntonMezger** [comment]
That was a choice we made. We fixed the font to a reasonable one. So not a bug. That is also the case for many other widgets.

Best regards

Anton

Envoyé de mon iPhone

Le 22 févr. 2018 à 18:58, Keenan Lang <notifications@github.com<mailto:notifications@github.com>> a écrit :


The caRelatedDisplay Font property doesn't do anything when changed in Qt Designer. Stylesheets, however, are capable of successfully modifying the font.

Steps to Replicate:

  *   Make a caRelatedDisplay
  *   Set stacking mode to Menu
  *   Set Label to "TEST"
  *   Set font family to anything
  *   Turn on Bold/Italic/Underline

Expected Result: Changing the font changes the display font of the label.

Actual Result: Nothing changes

**Comment by keenanlang** [comment]
>That is also the case for many other widgets.

Is there a methodology behind which widgets can or cannot have their fonts set? 

Because looking over all the widgets, it seems strange that the caScriptButton would be able to be changed when the caRelatedDisplay and the caShellCommand cannot. And similarly why the gauge widgets can change the font of their axes, but the plot widgets cannot.

**Comment by AntonMezger** [comment]
I fixed calineedit and calinedraw to a non proportionnal font. However in case of a carelateddisplay, the font is the default of qpushbutton when the carelateddisplay gets initialized. The font that you change has no impact later on and only by changing the stylesheet, that will give all childs the font you wanted, you can change the font at creating the widget
