### ISSUE TITLE
Font scaling messes with grid layout

### ISSUE THREAD

**Issue by keenanlang** [caqtdm/caqtdm#37]
The font scaling in widgets like caLabel makes it so that a widget cannot be stretched to span multiple cells in a grid layout.

### Steps to Replicate:

- Make a caLineEdit
- Place it in a gridLayout
- Add a widget to the east of the caLineEdit
- Add a widget to the southeast of the caLineEdit
- Stretch the caLineEdit to span into the remaining empty cell

**Expected Result**: The widget should take up the space of both cells

**Actual Result**: The widget refuses to stretch. 

With different setups and different widgets, the widget's boundaries will move as you stretch it, but the widget itself will constantly try to resize itself, flashing between the maximum boundary size and its original size, this also stops the widget from working with the grid layout. Switching off FontScaling allows the widget to be stretched correctly.

Note: The caLed widget with the scalable property (and gradient turned off) also resizes as it is stretched in a grid layout, but it does not interfere with the ability to span multiple cells.

**Comment by AntonMezger** [comment]
I could not reproduce this problem with my actual version. Could you send an ui file that reproduces this behaviour.

best regards
Anton


________________________________

**Comment by keenanlang** [comment]
[example.ui.zip](https://github.com/caqtdm/caqtdm/files/1759372/example.ui.zip)

**Comment by AntonMezger** [comment]
Hi,

In order to stretch, one first has to set the fontscaling to none, then stretch the calineedit and set again fontscaling to widthandheight. In our latest version no flashing can be reproduced and it works perfectly well. What Version you are working with?

best regards

Anton

________________________________

**Comment by keenanlang** [comment]
>In order to stretch, one first has to set the fontscaling to none, then stretch the calineedit and set again fontscaling to widthandheight.

I know, that's what I reported as an issue, the fact that you have to disable and reenable fontscaling to be able to use a basic feature of qt.

>In our latest version no flashing can be reproduced and it works perfectly well

The flashing isn't a part of the calineedit example, I just hadn't figured out a reproduceable example at that point to put into the example. I have since managed to do so and have attached it to this comment. It's the exact same problem as the calineedit, it's just that you can see the widget constantly resizing itself back to a single grid cell as you drag.

[example2.ui.zip](https://github.com/caqtdm/caqtdm/files/1763579/example2.ui.zip)

**Comment by AntonMezger** [comment]
Well,

The fact that you can stretch wih fontscaling None and afterwards setting fontscaling to widthandheight also solves the problem with your new example. Be aware of the fact that automatic fontresizing with layouts has to be done like that. I do not consider that really as an issue.
