### ISSUE TITLE
font sytle of caStripPlot

### ISSUE THREAD

**Issue by dschick** [caqtdm/caqtdm#41]
Hej,

I am trying with a stylesheet to change to size and color of the `caStripPlot `axis lables, etc.
Till now I can only change the `background-color`.

Any help?

Thanks in advance,

Daniel

**Comment by AntonMezger** [comment]
Hi,

I never tried, while normally the colors are set by properties.

Best regards

Anton

Envoyé de mon iPhone

**Comment by dschick** [comment]
yeah ,the property was somehow not working for me.
I found a workaround using a stylesheet:
```
caStripPlot  * {
	color: #ffffff;
	font-size: 20px;
}
```
This works for the tick labels but the size is not working for the axis labels.
Do you have the according css sublasses at hand for the caStripPlot - if there are any?

Thanks for the quick reply

Daniel

**Comment by AntonMezger** [comment]
Hi,

If you fix fonts with a stylesheet, it is possible that resizing does not work properly

Best regards

Anton

Envoyé de mon iPhone

**Comment by dschick** [comment]
okay thanks, I am closing this issue then.
