### ISSUE TITLE
caStripPlot with log10 fails on Raspi

### ISSUE THREAD

**Issue by dschick** [caqtdm/caqtdm#42]
I run caQtDM on a raspi with lastest raspbian installed.
It seems that everything works fine expect the caStripPlot when the y-axis is in log10 mode.
Then the ui is not loading or crashes when changed dynamically.

Is this related to qwt is there any other package necessary to do the conversion?

Best

Daniel

**Comment by AntonMezger** [comment]
Do you use the latest version from git development? Which version of Qt and qwt? Does gdb gives you an indication? 

Where are you located?

Best regards

Anton

Envoyé de mon iPhone

**Comment by dschick** [comment]
Hej Anton,

Qt is 4.8.7
qwt is 6.1.2-6

I have not worked with gdb so far ... could you briefly tell me what command I should run to get any debugging informations?

I am located at Max-Born-Institute in Berlin, close to BESSY II

Best

Daniel

**Comment by dschick** [comment]
so the data should be all fine: no negative data and no nan. I am plotting pressures from a gauge which is normally 1e-7.
This is actually working fine on Windows and Linux-x64 - the problem is only there for the raspi.

I tried with gdb:
- in Terminal 1, I run: `gdb caQtDM`
- in Terminal 2, I run: `caQtDM /path/to/my/UIs/testLog10.ui`
- I change the y-axis from lin to log10 and the UI crashes
- in Termin 1, I type: `bt`
- output is `No stack`

**Comment by dschick** [comment]
yes, it crashes then as well, always after some time like 30s on the raspi - the ui will not even show up.

**Comment by AntonMezger** [comment]
I never saw a behaviour like that an I do not have a raspberry either to test that out. Perhaps you could try to have an older or newer version of qwt built against your actual version of qt. Otherwise the only thing that could be done, is to lent me a raspberry you configured.

Best regards

Anton

Envoyé de mon iPhone

**Comment by HelgeBrands** [comment]
It seem to be solved
