### ISSUE TITLE
4.2.4 builds (needing rpc hack) but crashes on Fedora 30

### ISSUE THREAD

**Issue by newville** [caqtdm/caqtdm#50]
I am trying to get caQtDM to build on Fedora 30.  As with #40, I got an error message about `rpc` include files not being found.  Though that conversation says (https://github.com/caqtdm/caqtdm/issues/40#issuecomment-395426038) that this was fixed, that is not true.  Changing `caQtDM_Viewer\qtdefs.pri` to once again read

```
# for some architectures this has to be defined for scan2D
macx | win32 | ios | unix | android {
DEFINES += XDR_HACK
DEFINES += XDR_LE
CONFIG += XDR_HACK
}
```

fixes the build problem and I can then build caQtDM.

Once built, caDtDM runs for me with a very simple screens but fails immediately with other screens, typically with
```
rabbit:~>caQtDM 00Start.ui
Qt: Session management error: Could not open network socket
caQtDM -- file <caQtDM_stylesheet.qss> could not be loaded, is 'CAQTDM_DISPLAY_PATH' </corvette/home/epics/ui/all> defined?
caQtDM -- file = <00Start.ui>
caQtDM -- viewer will disable monitors for hidden pages of QTabWidgets, in case of problems
          you may disable this by not defining IO_OPTIMIZED_FOR_TABWIDGETS in qtdefs.pri
caQtDM -- files will not be downloaded from an url when not locally found, while CAQTDM_URL_DISPLAY_PATH is not defined
caQtDM -- Suspend epics connections for data in invisible tabs while CAQTDM_OPTIMIZE_EPICS3CONNECTIONS not set to TRUE
Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.
double free or corruption (out)
KCrash: Application 'caQtDM' crashing...
Alarm clock
```

**Comment by HelgeBrands** [comment]
the qtdefs.pri is the central config for the compilation. Sorry we can‘t forseen all distributions so a few things could be needed. 
The crash is a little bit less informative. Can you send me some more details like a backtrace or checkout the Development branch. I found some thing where we run with some Qt calls into problems.

**Comment by newville** [comment]
@HelgeBrands 

> the qtdefs.pri is the central config for the compilation. Sorry we can‘t forseen all distributions so a few things could be needed.

Well, the fix the `rpc` include file is the change that *you* suggested when I raised the same issue in June 2018 (#40) with Fedora 28 (which is the basis for RHEL8/Centos8).

Indeed, adding that "XRD_HACK" fixed the problem for Fedora 28 (and RHEL8/Centos8), and it fixes it for Fedora 30.   

FWIW, Fedora 30 is using Qt 5.12.  I don't know why the 

```
# enable XDR_HACK test for Linux/Qt5.10 e.g. Fedora 28
unix:!macx:{
 contains(QT_VER_MAJ, 5) {
   greaterThan(QT_VER_MIN,9){
    DEFINES += XDR_HACK
    DEFINES += XDR_LE
    CONFIG += XDR_HACK
   }
 }
}
```

fails.  Perhaps Qmake's `greaterThan` does a string comparison?

>The crash is a little bit less informative. Can you send me some more details like a backtrace or checkout the Development branch. I found some thing where we run with some Qt calls into problems.

What I sent was the full set of messages from 4.2.4.   Sorry, I do not understand the build system well enough to know how to turn on debugging.   I'll try building with the development branch next week.

**Comment by newville** [comment]
@HelgeBrands I rebuilt from github master branch and things have been running stably for at least an hour.  Screens that were causing 4.2.4 to crash are working now.

**Comment by HelgeBrands** [comment]
To test the crashing caqtdm start it with

`gdb —args caqtdm failurepanel.ui`

and when you get the promt from gdb then type run to start the caqtdm. When the crash happens then type `bt` for the backtrace. Them send me the output. 
The crashing panel files could be helpfull too.

**Comment by newville** [comment]
@HelgeBrands  I now believe that the crashes I was seeing were due to conflicting libraries.  That is, the crashing `caQtDM` executable was loading the wrong `libcaQtDM_Lib.so`.   I have not seen a crash since I got all the paths correct (and removed the older versions).  

So, I think we can close this, except that better install instructions would be greatly appreciated.
