### ISSUE TITLE
converted MEDM screen renders differently on v4.2.5

### ISSUE THREAD

**Issue by prjemian** [caqtdm/caqtdm#52]
A screen converted (by adl2ui) renders differently on v4.2.5 than it does with v4.2.0.

Here's the view of that screen with 4.2.0 (compared with MEDM original on the left):
![Clipboard01](https://user-images.githubusercontent.com/2279984/76691525-9a781d00-6619-11ea-9c30-a759f48f102e.jpg)

Same comparison (on a different workstation and IOC instance) but using 4.2.5_Development (from recent github master):
![Clipboard02](https://user-images.githubusercontent.com/2279984/76691614-8123a080-661a-11ea-9a1c-2b076529ee71.jpg)

Here are my commands to load the screens from GitHub and call them up in MEDM and caQtDM:

```
cd /tmp
git clone https://github.com/epics-modules/calc
cd calc/calcApp/op/
medm -x -macro "P=sky:,C=userCalc1" adl/userCalc.adl  &
caQtDM -macro "P=sky:,C=userCalc1" ui/autoconvert/userCalc.ui &
```

Has something changed in caQtDM to produce this effect?

**Comment by prjemian** [comment]
Originally reported here: https://github.com/epics-modules/calc/issues/22

**Comment by HelgeBrands** [comment]
Hi Pete,

can you give us first some information about your environment or is it the exactly the same environment. I guess I missed some version information: You version is 4.2.5?

We need:
Qt Version
Linux distribution
and it would be nice if you could test with the master branch if the same problem happend.

Can you send me the difference in the ui file?

Best regards
       Helge

Am 14.03.2020 um 23:40 schrieb Pete R Jemian <notifications@github.com>:

﻿

A screen converted (by adl2ui) renders differently on v2.4.5 than it does with v2.4.0.

Here's the view of that screen with 2.4.0 (compared with MEDM original on the left):
[Clipboard01]<https://user-images.githubusercontent.com/2279984/76691525-9a781d00-6619-11ea-9c30-a759f48f102e.jpg>

Same comparison (on a different workstation and IOC instance) but using 2.4.5_Development (from recent github master):
[Clipboard02]<https://user-images.githubusercontent.com/2279984/76691614-8123a080-661a-11ea-9a1c-2b076529ee71.jpg>

Here are my commands to load the screens from GitHub and call them up in MEDM and caQtDM:

cd /tmp
git clone https://github.com/epics-modules/calc
cd calc/calcApp/op/
medm -x -macro "P=sky:,C=userCalc1" adl/userCalc.adl  &
caQtDM -macro "P=sky:,C=userCalc1" ui/autoconvert/userCalc.ui &


Has something changed in caQtDM to produce this effect?

**Comment by prjemian** [comment]
Thanks for the quick reply.  The example from v4.2.0 is on a RHEL7 workstation at the APS, the v4.2.5 example is from the master branch downloaded March 6 and built on my linux mint VM.

> A screen converted (by adl2ui) renders differently on v2.4.5 than it does with v2.4.0.

That is important.  I'm certain these screens were not converted with some version *before* v4.2.5.

Here is the output of `bash caQtDM_Env` from my build environment:

```

====== do not use psi trolltech directories

=============================================================================================
in order to build this package you will eventually have to redefine following variables in
this file, they are taken from your environment if they exist, otherwise define them yourself:

for building:

QTHOME now defined as /usr/local/Qt/5.12.1/gcc_64 for locating Qt
QWTHOME now defined as /usr/local/qwt-6.1.4 for locating qwt
QWTINCLUDE now defined as /usr/local/qwt-6.1.4/include for locating the include files of qwt
QWTLIB now defined as /usr/local/qwt-6.1.4/lib for locating the libraries of qwt
EPICS_BASE now defined as /usr/local/epics/base-7.0.2 for locating epics
EPICSINCLUDE now defined as /usr/local/epics/base-7.0.2/include for locating epics include files
EPICSLIB now defined as /usr/local/epics/base-7.0.2/lib/linux-x86_64 for locating epics libraries
QTBASE now defined as /home/mintadmin/Documents/eclipse/caqtdm/caQtDM_Binaries for building the package locally, pointing to caQtDM_Binaries
QTDM_RPATH now defined as /usr/local/epics/opi/lib/linux-x86_64:/binQt:/home/mintadmin/Documents/eclipse/caqtdm/caQtDM_Binaries for runtime search path

libraries for channel access archive and logging archive:

CAQTDM_LOGGING_ARCHIVELIBS now defined as /home/mintadmin/Documents/eclipse/caqtdm/caQtDM_Binaries for logging archive rpc library
CAQTDM_CA_ARCHIVELIBS now defined as /home/mintadmin/Documents/eclipse/caqtdm/caQtDM_Binaries for channel access archive library

for python:

PYTHONVERSION now defined as 3.6m for locating python
PYTHONINCLUDE now defined as /usr/include/python3.6m for locating python include files
PYTHONLIB now defined as /usr/lib/ for locating python libraries

for zmq:

ZMQINC now defined as /usr/local/include for locating zmq include files
ZMQLIB now defined as /usr/local/lib for locating zmq libraries

for install:

EPICSEXTENSIONS now defined as /usr/local/epics/opi for locating epics extensions
QTDM_LIBINSTALL now defined as /usr/local/epics/opi/lib/linux-x86_64 for libraries install
QTDM_BININSTALL now defined as /usr/local/epics/opi/bin/linux-x86_64 for binaries install
============================================================================================
```

And you are correct, I built with the Development branch.  Will pull the master branch and build with it next, then retest.

**Comment by prjemian** [comment]
Here's the same screen (not rebuilt) using a rebuild of caQtDM from the *master* branch (for sure master, not Development).  It's labeled in the window above the screen.

This rendering looks as expected. 

I'll accept that it is necessary to make sure the build is on the master branch and not Development.

**Comment by prjemian** [comment]
![Clipboard01](https://user-images.githubusercontent.com/2279984/76692363-80dbd300-6623-11ea-86ed-c2a3ce2b5620.jpg)

**Comment by prjemian** [comment]
Will we need need to be prepared to rebuild our screens when v4.2.5 is released?

**Comment by MarkRivers** [comment]
> Will we need need to be prepared to rebuild our screens when v4.2.5 is released?

I certainly hope not.  That would be equivalent of learning that screens created with an earlier version of medm don't display correctly on a later version of medm.  That has never happened, and I hope it doesn't with caQtDM.

**Comment by AntonMezger** [comment]
Hello, 

without any data acquisition from an ioc, we can not study your problem. Do you have some better example?

Best regards

Anton

**Comment by AntonMezger** [comment]
Certainly not, we must stay compatible and we will try to find out what is wrong!

Best regards

Anton

**Comment by prjemian** [comment]
Can you run a [docker](https://www.docker.com/) container?  If so, you can start the [same IOC](https://github.com/prjemian/epics-docker/tree/master/n3_synApps#one-time-setup) and view the same PVs (without the custom calc configuration for a noisy lorentzian):

### one-time setup

(assumes `~/bin` is on your `PATH`)

```
 cd ~/bin
 wget https://raw.githubusercontent.com/prjemian/epics-docker/master/n3_synApps/start_xxx.sh
 wget https://raw.githubusercontent.com/prjemian/epics-docker/master/n3_synApps/remove_container.sh
```

### start the *sky* IOC shown above, then start *caQtDM*

The first time starting the IOC loads the images from docker, subsequent starts skip that part automatically.

```
start_xxx.sh sky
/tmp/docker_ioc/iocsky/xxx-R6-1/start_caQtDM_xxx
```

This will start a screen with blue buttons at the top and a grid of green buttons.  Click the blue button marked *Tools* and this is what I see:

![Clipboard01](https://user-images.githubusercontent.com/2279984/76706903-02317500-66b9-11ea-96c8-4059a04776e9.jpg)

Click the green button *userCalc* and select the first item *user calcs 1-10*.  Yours will look similar (you won't have the noisy Lorentzian and the *Disable* will be selected).  Mine looks like:

![Clipboard02](https://user-images.githubusercontent.com/2279984/76706946-5f2d2b00-66b9-11ea-8614-471ed14c92b0.jpg)

Click the green button in the left column marked *5* and select the first item *user Calc 5*.  Again, yours should look identical to mine (since this calc has default settings):

![Clipboard03](https://user-images.githubusercontent.com/2279984/76706996-bcc17780-66b9-11ea-850d-e9bf15117100.jpg)

**Comment by prjemian** [comment]
BTW: You *could* (if you wanted to) apply the configuration for the noisy lorentzian using the settings you see above.  The computed value is tied to the position of `sky:m1`, a soft motor record.

**Comment by AntonMezger** [comment]
Hi Pete,

Sorry, I did not understand your message. I would like an epics database for the variables in order to put them in a softie.

Best Regards

Anton

**Comment by prjemian** [comment]
If run this in the `softIoc` application, you'll also need a `.dbd` file that adds definitions for the modules not in EPICS base.

The database for these calcs is from synApps userCalcs, loaded [from this code](https://github.com/epics-modules/xxx/blob/a36fee4baf1a241231d3e0bd800ddc5b216cf20d/iocBoot/iocxxx/common.iocsh) at these lines which refer to the CALC module:

```
### Stuff for user programming ###
iocshLoad("$(CALC)/iocsh/userCalc.iocsh", "PREFIX=$(PREFIX), ARRAY_SIZE=8000")
```

The relevant databases are [loaded by these lines](https://github.com/epics-modules/calc/blob/master/iocsh/userCalc.iocsh):

```
# ### userCalc.iocsh ###

#- ###################################################
#- PREFIX         - IOC Prefix
#- CALC           - Location of Calc module
#- ARRAY_SIZE     - Optional: Size of userArrayCalc array
#-                  Default:  8000
#- ###################################################


#- ## Stuff for user programming ###
dbLoadRecords("$(CALC)/calcApp/Db/userCalcGlobalEnable.db", "P=$(PREFIX)")
dbLoadRecords("$(CALC)/calcApp/Db/userCalcs10.db",          "P=$(PREFIX)")
dbLoadRecords("$(CALC)/calcApp/Db/userCalcOuts10.db",       "P=$(PREFIX)")
dbLoadRecords("$(CALC)/calcApp/Db/userStringCalcs10.db",    "P=$(PREFIX)")
dbLoadRecords("$(CALC)/calcApp/Db/userArrayCalcs10.db",     "P=$(PREFIX), N=$(ARRAY_SIZE=8000)")
dbLoadRecords("$(CALC)/calcApp/Db/userTransforms10.db",     "P=$(PREFIX)")
dbLoadRecords("$(CALC)/calcApp/Db/userAve10.db",            "P=$(PREFIX)")
```

All these `.db` files are in this directory:
https://github.com/epics-modules/calc/tree/master/calcApp/Db

**Comment by AntonMezger** [comment]
I will try tomorrow

**Comment by AntonMezger** [comment]
Hi Pete,


For some reason Helge modified the stylesheet  of camenu. In order to be compatible change it back by taking the padding and min-width off in setcolors of camenu.cpp.

I do not correct that in git now before discussing this with helge, while I do not know why that got in.

I hope that solves your problem. I did not test more, so that if there is still something wrong tell us.

Best regards 

Anton

**Comment by prjemian** [comment]
Thanks for identifying the root cause.  For now, I'll continue to use the production version (4.2.0), realizing that comes from the *master* branch.

**Comment by prjemian** [comment]
Perhaps we leave this issue open until you and @HelgeBrands make a decision?

**Comment by AntonMezger** [comment]
Hi,

I discussed with Helge and we decided to correct that stylesheet after you have found the problem solved. Then it will be put in the development path and feature/acm paths.

Best regards

Anton

**Comment by prjemian** [comment]
Thanks!  To be clear, I should first confirm that when I change the stylesheet (for a build of 4.2.5 from the Development branch), that the problem is fixed. Correct?

**Comment by AntonMezger** [comment]
Hi,

Yes that is the idea!

**Comment by prjemian** [comment]
Two instances:

https://github.com/caqtdm/caqtdm/blob/0f758b26eb3547637b52eb7af7d41d7ee0670d06/caQtDM_QtControls/src/camenu.cpp#L117

https://github.com/caqtdm/caqtdm/blob/0f758b26eb3547637b52eb7af7d41d7ee0670d06/caQtDM_QtControls/src/camenu.cpp#L122

**Comment by prjemian** [comment]
Each will be changed to:

```
thisStyle = "caMenu {background-color: rgba(%1, %2, %3, %4); color: rgba(%5, %6, %7, %8);}"; ```

**Comment by prjemian** [comment]
by the way, to rebuild, I'm doing a CleanAll, then BuildAll, then Install

**Comment by prjemian** [comment]
## Fixes the problem!

### before the change

![before](https://user-images.githubusercontent.com/2279984/76793025-45abe200-6792-11ea-95b6-b7e81f730b91.jpg)

### after the change

![after](https://user-images.githubusercontent.com/2279984/76793031-480e3c00-6792-11ea-9be5-f4516d38939e.jpg)

**Comment by prjemian** [comment]
The stylesheet in `caMenu::setColors()` also sets the background and foreground colors.  This overrides what is set in the [`userCalc.ui`](https://github.com/epics-modules/calc/blob/master/calcApp/op/ui/autoconvert/userCalc.ui#L552-L565) file (it is set by the *adl2ui* program):

```
            <property name="foreground">
                <color alpha="255">
                    <red>0</red>
                    <green>0</green>
                    <blue>0</blue>
                </color>
            </property>
            <property name="background">
                <color alpha="255">
                    <red>115</red>
                    <green>223</green>
                    <blue>255</blue>
                </color>
            </property>
```

This is not a major problem but it is nice if we can configure the color of the popup menu from the `.ui` file.

**Comment by AntonMezger** [comment]
However, it seems to me that the colors are missing?

Envoyé de mon iPhone

**Comment by prjemian** [comment]
As shown [above](https://github.com/caqtdm/caqtdm/issues/52#issue-581402483), there is a change in the background color of the caMenu.

**Comment by prjemian** [comment]
BUT, observe the background color of the MEDM widget is grey, not blue.  Obviously not a major problem.

**Comment by prjemian** [comment]
Ah.  The missing colors *should* come from the property and populate this expression:

    background-color: rgba(%1, %2, %3, %4); color: rgba(%5, %6, %7, %8)

the default values are set by these lines:
https://github.com/caqtdm/caqtdm/blob/0f758b26eb3547637b52eb7af7d41d7ee0670d06/caQtDM_QtControls/src/camenu.cpp#L117-L119

and for newer settings (such as from the `.ui` file), these lines:
https://github.com/caqtdm/caqtdm/blob/0f758b26eb3547637b52eb7af7d41d7ee0670d06/caQtDM_QtControls/src/camenu.cpp#L122-L124

**Comment by AntonMezger** [comment]
I still have to see why it behaves differently from the color point of view

Envoyé de mon iPhone

**Comment by prjemian** [comment]
Ok.  Feel free to close this issue when you satisfied.  Thanks for your attention.

**Comment by AntonMezger** [comment]
You may try camenu.cpp from the branch feature/acm. Colors should again be ok by now. 

Best regards

Anton

**Comment by prjemian** [comment]
Getting there but many, many interruptions today.

**Comment by prjemian** [comment]
Something bad happened with that branch.  The main screen opens, displays OK, but caQtDM cannot find any related display screens on the display path.  Recompiled, thinking something might have gone wrong (it has been a busy day with lots of interruptions), no.  Switched to master branch and recompiled again.  Exact same starter shell script in use, and related displays open.

Ideas?

**Comment by AntonMezger** [comment]
Hi,

I tested on my centos and related displays open on the display path, so I cannot see what is going wrong? Does it tell you something in the message window?

Helge, can you test also feature/acm for related displays?

Best regards

Anton

**Comment by HelgeBrands** [comment]
I started with tests from the Development branch. But I don't see any error. 
All commits are now in the Develoment Branch

**Comment by prjemian** [comment]
Just changed to Development branch, did `git pull` just in case, then re-compiled.  With the "green button screen" from synApps xxx module, I get the same error when selecting the related display button for the motors 1-8, motors 9-16, ...

![Clipboard01](https://user-images.githubusercontent.com/2279984/77165404-32459300-6a80-11ea-93f2-25ce77e6eb2f.jpg)

The starter script is attached (it's bash but `.txt` added so GitHub will accept it):
[start_caQtDM_xxx.txt](https://github.com/caqtdm/caqtdm/files/4359629/start_caQtDM_xxx.txt)

**Comment by prjemian** [comment]
So, I *simplified* the situation and do not see the same problem:

<details>
<summary>bash starter  script</summary>
<p>

```
#!/bin/bash

export CAQTDM_DISPLAY_PATH=.:/tmp:${HOME}/Documents/demo-screens
export CAQTDM_OPTIMIZE_EPICS3CONNECTIONS=true
export QT_PLUGIN_PATH=/usr/local/epics/extensions/lib/linux-x86_64
caQtDM -style plastique -noMsg screen1.ui
```

</p>
</details>

<details>
<summary>screen1.ui</summary>
<p>

```
<?xml version="1.0" encoding="UTF-8"?>
<ui version="4.0">
<class>MainWindow</class>
<widget class="QMainWindow" name="MainWindow">
    <property name="geometry">
        <rect>
            <x>0</x>
            <y>25</y>
            <width>216</width>
            <height>133</height>
        </rect>
    </property>
    <property name="styleSheet">
        <string>

QWidget#centralWidget {background: rgba(187, 187, 187, 255);}

</string>
    </property>
    <widget class="QWidget" name="centralWidget">
        <widget class="caLabel" name="caLabel_0">
            <property name="frameShape">
                <enum>QFrame::NoFrame</enum>
            </property>
            <property name="foreground">
                <color alpha="255">
                    <red>0</red>
                    <green>0</green>
                    <blue>0</blue>
                </color>
            </property>
            <property name="background">
                <color alpha="0">
                    <red>0</red>
                    <green>0</green>
                    <blue>0</blue>
                </color>
            </property>
            <property name="text">
                <string>screen 1</string>
            </property>
            <property name="fontScaleMode">
                <enum>ESimpleLabel::WidthAndHeight</enum>
            </property>
            <property name="geometry">
                <rect>
                    <x>14</x>
                    <y>10</y>
                    <width>154</width>
                    <height>31</height>
                </rect>
            </property>
            <property name="alignment">
                <set>Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter</set>
            </property>
        </widget>
        <widget class="caRelatedDisplay" name="caRelatedDisplay_0">
            <property name="geometry">
                <rect>
                    <x>16</x>
                    <y>41</y>
                    <width>157</width>
                    <height>27</height>
                </rect>
            </property>
            <property name="foreground">
                <color alpha="255">
                    <red>0</red>
                    <green>0</green>
                    <blue>0</blue>
                </color>
            </property>
            <property name="background">
                <color alpha="255">
                    <red>187</red>
                    <green>187</green>
                    <blue>187</blue>
                </color>
            </property>
            <property name="label">
                <string>open screen 2</string>
            </property>
            <property name="stackingMode">
                <enum>Menu</enum>
            </property>
            <property name="labels">
                <string>open screen2</string>
            </property>
            <property name="files">
                <string>screen2.adl</string>
            </property>
            <property name="args">
                <string></string>
            </property>
            <property name="removeParent">
                <string>false</string>
            </property>
        </widget>
        <widget class="caRelatedDisplay" name="caRelatedDisplay_1">
            <property name="geometry">
                <rect>
                    <x>16</x>
                    <y>84</y>
                    <width>157</width>
                    <height>27</height>
                </rect>
            </property>
            <property name="foreground">
                <color alpha="255">
                    <red>0</red>
                    <green>0</green>
                    <blue>0</blue>
                </color>
            </property>
            <property name="background">
                <color alpha="255">
                    <red>187</red>
                    <green>187</green>
                    <blue>187</blue>
                </color>
            </property>
            <property name="label">
                <string>open screen 3</string>
            </property>
            <property name="stackingMode">
                <enum>Menu</enum>
            </property>
            <property name="labels">
                <string>open screen3</string>
            </property>
            <property name="files">
                <string>screen3.adl</string>
            </property>
            <property name="args">
                <string></string>
            </property>
            <property name="removeParent">
                <string>false</string>
            </property>
        </widget>
        <zorder>caLabel_0</zorder>
        <zorder>caRelatedDisplay_0</zorder>
        <zorder>caRelatedDisplay_1</zorder>
    </widget>
</widget>
</ui>
```

</p>
</details>

<details>
<summary>screen2.ui</summary>
<p>

```
<?xml version="1.0" encoding="UTF-8"?>
<ui version="4.0">
<class>MainWindow</class>
<widget class="QMainWindow" name="MainWindow">
    <property name="geometry">
        <rect>
            <x>0</x>
            <y>25</y>
            <width>216</width>
            <height>133</height>
        </rect>
    </property>
    <property name="styleSheet">
        <string>

QWidget#centralWidget {background: rgba(187, 187, 187, 255);}

</string>
    </property>
    <widget class="QWidget" name="centralWidget">
        <widget class="caLabel" name="caLabel_0">
            <property name="frameShape">
                <enum>QFrame::NoFrame</enum>
            </property>
            <property name="foreground">
                <color alpha="255">
                    <red>0</red>
                    <green>0</green>
                    <blue>0</blue>
                </color>
            </property>
            <property name="background">
                <color alpha="0">
                    <red>0</red>
                    <green>0</green>
                    <blue>0</blue>
                </color>
            </property>
            <property name="text">
                <string>screen 2</string>
            </property>
            <property name="fontScaleMode">
                <enum>ESimpleLabel::WidthAndHeight</enum>
            </property>
            <property name="geometry">
                <rect>
                    <x>14</x>
                    <y>10</y>
                    <width>154</width>
                    <height>31</height>
                </rect>
            </property>
            <property name="alignment">
                <set>Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter</set>
            </property>
        </widget>
        <widget class="caRelatedDisplay" name="caRelatedDisplay_0">
            <property name="geometry">
                <rect>
                    <x>16</x>
                    <y>41</y>
                    <width>157</width>
                    <height>27</height>
                </rect>
            </property>
            <property name="foreground">
                <color alpha="255">
                    <red>0</red>
                    <green>0</green>
                    <blue>0</blue>
                </color>
            </property>
            <property name="background">
                <color alpha="255">
                    <red>187</red>
                    <green>187</green>
                    <blue>187</blue>
                </color>
            </property>
            <property name="label">
                <string>open screen 1</string>
            </property>
            <property name="stackingMode">
                <enum>Menu</enum>
            </property>
            <property name="labels">
                <string>open screen1</string>
            </property>
            <property name="files">
                <string>screen1.adl</string>
            </property>
            <property name="args">
                <string></string>
            </property>
            <property name="removeParent">
                <string>false</string>
            </property>
        </widget>
        <widget class="caRelatedDisplay" name="caRelatedDisplay_1">
            <property name="geometry">
                <rect>
                    <x>16</x>
                    <y>83</y>
                    <width>157</width>
                    <height>27</height>
                </rect>
            </property>
            <property name="foreground">
                <color alpha="255">
                    <red>0</red>
                    <green>0</green>
                    <blue>0</blue>
                </color>
            </property>
            <property name="background">
                <color alpha="255">
                    <red>187</red>
                    <green>187</green>
                    <blue>187</blue>
                </color>
            </property>
            <property name="label">
                <string>open screen 3</string>
            </property>
            <property name="stackingMode">
                <enum>Menu</enum>
            </property>
            <property name="labels">
                <string>open screen3</string>
            </property>
            <property name="files">
                <string>screen3.adl</string>
            </property>
            <property name="args">
                <string></string>
            </property>
            <property name="removeParent">
                <string>false</string>
            </property>
        </widget>
        <zorder>caLabel_0</zorder>
        <zorder>caRelatedDisplay_0</zorder>
        <zorder>caRelatedDisplay_1</zorder>
    </widget>
</widget>
</ui>
```

</p>
</details>

![Clipboard02](https://user-images.githubusercontent.com/2279984/77166250-e85dac80-6a81-11ea-8c4f-3dc8da879b02.jpg)

**Comment by prjemian** [comment]
needs more study on my end to identify the differences between the two examples I've shown

**Comment by prjemian** [comment]
The "open screen 3" button is to demonstrate what happens when a related display screen is not found.  There is no `screen3.ui` file.

**Comment by HelgeBrands** [comment]
the best is to check CAQTDM_DISPLAY_PATH and the executable path because in your pictures you can see the variable CAQTDM_INTERNAL_UIPATH. But the commandline tabs are showing something with eclipse

**Comment by prjemian** [comment]
I've create a repository to make it easier to share screens and scripts: 
https://github.com/prjemian/demo-screens

**Comment by HelgeBrands** [comment]
the problem you see is the .adl ending in your related display!

**Comment by prjemian** [comment]
I'll check that, for sure.  But the same starter script (for the green button screen) works fine with master branch.  So something has changed in caQtDM.

Also, for some years I used *eclipse* as my project editor, so my projects are stored under `~/Documents/eclipse/<project>`.  Using a different editor but still the directories remain in that location.  Just a distraction.

**Comment by AntonMezger** [comment]
What changed in feature/acm is the fact that when you compile it with the option eel/adl files converting on the fly, then these files will be used and converted.

**Comment by prjemian** [comment]
Interesting.  I notice that in the many synApps screen files converted from MEDM by adl2ui, the related display still uses the `.adl` suffix rather than converting it to `.ui`.  Here's an example: https://github.com/prjemian/demo-screens/blob/eb409d557c3edfae682dbf56351d463e0d566552/caqtdm/screen1.ui#L89-L91

I've always thought that adl2ui should change the suffix.  If what you are saying is that caQtDM can now do this translation automatically, then the real problem is that the CAQTDM_DISPLAY_PATH should point to directories with `.adl` files (if that is the type referenced in the related display menu).  Agree?

**Comment by prjemian** [comment]
As you can see, I just confirmed that the Development branch of caQtDM autoconverts `.adl` files at runtime.  

The problem I reported (screen file not found) is because adl2ui named the converted screen file with  the `.ui` suffix but did not use this new name in the related display menu.  Thus, when the display path is set to directories which do not include `.adl` files, the related displays will not be found.

In the synApps modules, the pattern of placing screen files in application-specific directories is now important since the same file suffix [(`.ui`)](https://github.com/prjemian/demo-screens#demo-screens) is used by more than one EPICS display manager (caQtDM and PyDM).

**Comment by AntonMezger** [comment]
Lieber Helge,

 

Nicht sicher, was er jetzt noch möchte oder ist es erledigt?

 

Gruss

 

Anton

 

De : Helge Brands <notifications@github.com> 
Envoyé : vendredi 20 mars 2020 14:48
À : caqtdm/caqtdm <caqtdm@noreply.github.com>
Cc : Anton Mezger <antonmezger@gmail.com>; Comment <comment@noreply.github.com>
Objet : Re: [caqtdm/caqtdm] converted MEDM screen renders differently on v4.2.5 (#52)

 

the problem you see is the .adl ending in your related display!

**Comment by prjemian** [comment]
Please change the adl2ui translator so that it replaces `.adl` with `.ui` in related displays.  Then the new feature AND the existing behavior will both work.  We'll have to re-translate our screens but that is a small price to pay.

**Comment by MarkRivers** [comment]
> We'll have to re-translate our screens but that is a small price to pay.

Is there any reason for a change that requires re-translation?  That means people will not be able to use their existing screens with new versions of caQtDM?  Will new screens work on old versions of caQtDM?

**Comment by prjemian** [comment]
@MarkRivers : We could still use existing screens but need to change the CAQTDM_DISPLAY_PATH in the environment setup to include the `adl` directories.

**Comment by MarkRivers** [comment]
>@MarkRivers : We could still use existing screens but need to change the CAQTDM_DISPLAY_PATH in the environment setup to include the adl directories.

Does that mean that is doing the conversion on-the-fly each time it opens a related display, if that display is referring to an adl file?  That seems inefficient.

**Comment by prjemian** [comment]
Apparently, that is a compile option to use or not use.

**Comment by HelgeBrands** [comment]
Hey guys, this is the Development Branch and is not finished. Please let us decide what is a problem and what not. I will close this discussion now because there is no relation to the Topic of caMenu any more.

**Comment by prjemian** [comment]
@HelgeBrands : Would you open a new issue for this?  The discussion is productive.

**Comment by HelgeBrands** [comment]
@prjemian Please let me look into it.

**Comment by AntonMezger** [comment]
Hi,

It seems to me that if you do not enable ADL_EDL_FILES in qtdefs.pri., you should have the normal behaviour where an ui file is taken instead of an all file.

Is that correct?

Best regards

Anton

**Comment by HelgeBrands** [comment]
@prjemian Please check the Development branch!

**Comment by prjemian** [comment]
tomorrow

**Comment by prjemian** [comment]
Commented out these lines: https://github.com/caqtdm/caqtdm/blob/9fbe43ab6830a6196c0357b297fa2df1b1b4bd0e/caQtDM_Viewer/qtdefs.pri#L113-L116

* cleaned
* built
* installed
* converted synApps *.adl using `adl2ui`
* confirmed that `motorx.ui` uses `.adl` in its related display menu
* opened the motors 1-8 display, then opened motor 1
* opened the userCalcs, then opened userCalc1

This works, just like it used to work!
![Clipboard01](https://user-images.githubusercontent.com/2279984/77385845-52fb3a80-6d57-11ea-8250-072743f77848.jpg)

Now, add the instruction to the documentation and we are *good to go*.  Thanks!
