### ISSUE TITLE
Why is TROLLTECH used here?

### ISSUE THREAD

**Issue by prjemian** [caqtdm/caqtdm#58]
On this line: https://github.com/caqtdm/caqtdm/blob/9abca43e8b4aa3fbf0d9aa766f5b0a136c3d1027/caQtDM_Env#L62

Since it is used inside an `if ...` block that has already determined the symbol is empty, the line will include `:/binQt:` in the `QTDM_RPATH`.  While it causes no harm, it is not necessary.

Is there some other reason to keep `:$TROLLTECH/binQt` as part of this line?

**Comment by prjemian** [comment]
@HelgeBrands :
From the [Network Graph](https://github.com/caqtdm/caqtdm/network), it looks like new code is being committed to the `Release` branch.  This is confusing since there is also a `Development` branch, where new code under development might be expected.

I want to build locally and wonder from which branch I should use.  At this time, the most recent release is v4.4.0, so I will build from that tag, rather than the default `Development` or the  `Release` branch.

**Comment by HelgeBrands** [comment]
@prjemian : the release thing is my problem that I found during the release process a lot of problems that need to be fixed. At the moment I'm stuck in the release because of problems with the RPM for RedHat that is needed at PSI

The trolltech stuff needs to be removed. Because of there was a time where they used Qt 4.6.2 and I have to keep the support of Qt4 at the moment

**Comment by prjemian** [comment]
Ok, I understand.  I just created a fork with a new branch from `Release`.  Should I continue with a pull request at this time?

**Comment by HelgeBrands** [comment]
the pull request I will put into Development for testing. Yes please continue! Every help in the development is welcome.

**Comment by prjemian** [comment]
I'll do it that way, then.

**Comment by HelgeBrands** [comment]
is this the only change?

**Comment by prjemian** [comment]
For now, yes.

**Comment by HelgeBrands** [comment]
This is can do in the Release branch. This is a build change!
