### ISSUE TITLE
merge Sphinx docs with the existing home page: caqtdm.github.io

### ISSUE THREAD

**Issue by prjemian** [caqtdm/caqtdm#63]
... the next step is to describe how to merge the Sphinx docs setup in #62 with the existing home page: https://caqtdm.github.io/

Ideally, Sphinx would be used to reconstruct the entire caqtdm.github.io site.  I take it as a challenge to try.  First is to build offline.  Then, there are GitHub Actions workflows that automate publishing the site to caqtdm.github.io.

_Originally posted by @prjemian in https://github.com/caqtdm/caqtdm/issues/62#issuecomment-1683780205_

**Comment by HelgeBrands** [comment]
At the moment I don't have time to do the job, but I will do as much I can.

**Comment by prjemian** [comment]
I hope to do this

**Comment by HelgeBrands** [comment]
Do you have an idea what is wrong? I added a generated singlehtml to http://caqtdm.github.io/ but there seems to be a problem with the stylesheets. Did I miss something?

**Comment by prjemian** [comment]
This might be the [workflow](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-deploy-to-subdirectory-destination_dir) we need to push the Sphinx docs to a subdirectory.

I'm sure there is a conflict between stylesheets.  Perhaps later this week I can put my attention on it.

**Comment by HelgeBrands** [comment]
so I fixed some stuff. no it is looking better.

**Comment by HelgeBrands** [comment]
added additional information
