### ISSUE TITLE
Major alarm colour scheme for inputs should be revised 

### ISSUE THREAD

**Issue by simongregorebner** [caqtdm/caqtdm#7]
I open this issue to discuss this issue...

Currently, if there is a major alarm on an input field, the colour or the font changes from green (no alarm) to red. For colour-blind people there is no difference between the no-alarm and major alarm state.
This is far from optimal, if not very dangerous!

**Comment by AntonMezger** [comment]
Sorry, the alarm scheme will not be revised. First of all, the alarm scheme follows the MEDM alarm scheme and is used as such. However you have the possibility to define alarm handling on foreground as well as on background. In PEP you may have to define this if desired. I think you are merely looking for that.,

**Comment by simongregorebner** [comment]
As discussed, lets just change following thing:

If alarm handling is set on "on background", for a major alarm the background should be red and the font colour should be white.

**Comment by AntonMezger** [comment]
We have to think about it, while the bg and fg colours are configurable, so that it is not straightforward to change the font colour behaviour for every specific alarm.

**Comment by AntonMezger** [comment]
setting white on a red background gives less contrast then black on red, so I will keep the actual color scheme. Anyhow at PSI the actual color scheme is used for some 20 years and gives good results. No change therefore will be done in caQtDM.

**Comment by AntonMezger** [comment]
It is now possible to achieve white on red in case of a major alarm. this is now used in the pep emulation.
one defines in the general stylesheet for caLineEdit background as white and color as black. Then for the caLineEdit alarmHandling on background and colorMode as Alarm_Default.
