### ISSUE TITLE
<Enter> for caLineEdit puts cursor at position 0

### ISSUE THREAD

**Issue by newville** [caqtdm/caqtdm#8]
First, thanks very much for the work here -- I'm trying to move to caqtdm and liking it very much.  I'm not sure if this is an Issue or a Question, but I've noticed (and been bitten by) the behavior that hitting <Enter> for most (perhaps all) caLineEdit widgets moves the cursor from the last entry point to left-most position of the widget.    That is, if a caLineEdit (with `formatType=decimal` for a double PV) reads
```
    [3.00]
```
and one puts the cursor after the decimal point, types `1` and then `<Enter>`, the number then reads

```
    [3.10]
```
but that the cursor is no longer between the `1` and the following `0` (as I would have expected, where it last was, and how it works in medm and other widget toolkits), but to the left of the `3`. 

Is this the intended behavior?   I believe this is not an inherent feature of QLineEdit, but am not sure if this is a settable property of QLineEdit (or of caLineEdit) -- I don't see anything obvious, but haven't looked in detail at all properties.  I suspect it might be some part of the validation process is moving the cursor position, since if instead of a `1`, I type `a` (that is, an invalid number in a caLineEdit defined to have `formatType=decimal`) the cursor *does* stay in position, though the <Enter> is not processed in the same way. 

Any suggestions on how to allow the cursor to stay at current position? Thanks!

**Comment by AntonMezger** [comment]
This will be corrected in version 4.0 (already in git)

**Comment by newville** [comment]
Thanks!
