### ISSUE TITLE
caCartesianPlot does not show any data on Ubuntu-22.04 LTS / Mint-21.3

### ISSUE THREAD

**Issue by sergeys21** [caqtdm/caqtdm#86]
The plot just stays empty and the axes are not rescaling with no error messages in the console or in the calling terminal. The matching MEDM window from which the UI was generated shows data fine. The issue was observed with SIS48XX_plot.ui (attached).  CaQtDM was compiled with OS-supplied Qt-5.15.3, Qwt-6.1.4, Python-3.10.

[SIS38XX_plot.zip](https://github.com/user-attachments/files/17818323/SIS38XX_plot.zip)

**Comment by sergeys21** [comment]
Commenting line 2822 in caqtdm_lib.cpp :

thisString.removeAll(QString(""));

Solved the problem. The line was affecting the plots were no X-data were specified.

**Comment by HelgeBrands** [comment]
Thanks a lot for your testing. I corrected a little bit more. The bug fix is in the Release branch
