### ISSUE TITLE
Compiling issue on Ubuntu 10.04 32-bit

### ISSUE THREAD

**Issue by peterleban** [caqtdm/caqtdm#9]
I have fresh installation of Ubuntu 10.04 32-bit and want to compile caqtdm-3.9.4. I've tried 3 different EPICS base versions (3.15.2, 3.14.12.15 and 3.14.12.2). My qwt version is 6.0.1.

This is the last part of compiler output:
g++ -c -pipe -g -g -O2 -Wall -W -D_REENTRANT -fPIC -DIO_OPTIMIZED_FOR_TABWIDGETS -DPYTHON -DEPICS -DQT_NO_DEBUG -DQT_PLUGIN -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtUiTools -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I/usr/include/python2.6 -I/home/libera/epics/base-3.14.12.2/include/os/Linux -I. -I/usr/local/qwt-6.0.1/include -I/home/libera/epics/base-3.14.12.2/include -I../src -I../../caQtDM_QtControls/src -I../moc -o ../obj1/JSON.o ../src/JSON.cpp
../src/caqtdm_lib.cpp: In member function ‘bool CaQtDM_Lib::Python_Error(QWidget*, QString)’:
../src/caqtdm_lib.cpp:2134: error: ‘PyObject’ was not declared in this scope
../src/caqtdm_lib.cpp:2134: error: ‘ptype’ was not declared in this scope
../src/caqtdm_lib.cpp:2134: error: ‘ptraceback’ was not declared in this scope
../src/caqtdm_lib.cpp:2135: error: ‘PyErr_Fetch’ was not declared in this scope
../src/caqtdm_lib.cpp:2136: error: ‘PyString_AsString’ was not declared in this scope
../src/caqtdm_lib.cpp:2140: error: ‘Py_Finalize’ was not declared in this scope
../src/caqtdm_lib.cpp: In member function ‘bool CaQtDM_Lib::CalcVisibility(QWidget*, double&, bool&)’:
../src/caqtdm_lib.cpp:2258: error: ‘Py_Initialize’ was not declared in this scope
../src/caqtdm_lib.cpp:2260: error: ‘PyObject’ was not declared in this scope
../src/caqtdm_lib.cpp:2260: error: ‘pArgs’ was not declared in this scope
../src/caqtdm_lib.cpp:2260: error: ‘pValue’ was not declared in this scope
../src/caqtdm_lib.cpp:2260: error: ‘pValueA’ was not declared in this scope
../src/caqtdm_lib.cpp:2260: error: ‘pFunc’ was not declared in this scope
../src/caqtdm_lib.cpp:2261: error: ‘pGlobal’ was not declared in this scope
../src/caqtdm_lib.cpp:2261: error: ‘PyDict_New’ was not declared in this scope
../src/caqtdm_lib.cpp:2262: error: ‘pLocal’ was not declared in this scope
../src/caqtdm_lib.cpp:2273: error: ‘PyEval_GetBuiltins’ was not declared in this scope
../src/caqtdm_lib.cpp:2273: error: ‘PyDict_SetItemString’ was not declared in this scope
../src/caqtdm_lib.cpp:2283: error: ‘pNewMod’ was not declared in this scope
../src/caqtdm_lib.cpp:2283: error: ‘PyModule_New’ was not declared in this scope
../src/caqtdm_lib.cpp:2285: error: ‘PyModule_AddStringConstant’ was not declared in this scope
../src/caqtdm_lib.cpp:2288: error: ‘PyModule_GetDict’ was not declared in this scope
../src/caqtdm_lib.cpp:2291: error: ‘Py_file_input’ was not declared in this scope
../src/caqtdm_lib.cpp:2291: error: ‘PyRun_String’ was not declared in this scope
../src/caqtdm_lib.cpp:2292: error: expected primary-expression before ‘)’ token
../src/caqtdm_lib.cpp:2292: error: expected ‘)’ before numeric constant
../src/caqtdm_lib.cpp:2294: error: ‘Py_DECREF’ was not declared in this scope
../src/caqtdm_lib.cpp:2297: error: ‘Py_DECREF’ was not declared in this scope
../src/caqtdm_lib.cpp:2300: error: ‘PyObject_GetAttrString’ was not declared in this scope
../src/caqtdm_lib.cpp:2301: error: expected primary-expression before ‘)’ token
../src/caqtdm_lib.cpp:2301: error: expected ‘)’ before numeric constant
../src/caqtdm_lib.cpp:2308: error: expected ‘)’ before ‘pArgs’
../src/caqtdm_lib.cpp:2308: warning: suggest braces around empty body in an ‘if’ statement
../src/caqtdm_lib.cpp:2309: error: ‘PyFloat_FromDouble’ was not declared in this scope
../src/caqtdm_lib.cpp:2320: error: ‘PyFloat_FromDouble’ was not declared in this scope
../src/caqtdm_lib.cpp:2323: error: ‘PyTuple_SetItem’ was not declared in this scope
../src/caqtdm_lib.cpp:2326: error: ‘PyObject_CallObject’ was not declared in this scope
../src/caqtdm_lib.cpp:2327: error: expected primary-expression before ‘)’ token
../src/caqtdm_lib.cpp:2327: error: expected ‘)’ before numeric constant
../src/caqtdm_lib.cpp:2328: error: ‘PyFloat_AsDouble’ was not declared in this scope
../src/caqtdm_lib.cpp:2331: error: ‘Py_XDECREF’ was not declared in this scope
../src/caqtdm_lib.cpp:2338: error: ‘Py_XDECREF’ was not declared in this scope
/usr/bin/moc-qt4 -DIO_OPTIMIZED_FOR_TABWIDGETS -DPYTHON -DEPICS -DQT_NO_DEBUG -DQT_PLUGIN -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtUiTools -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I/usr/include/python2.6 -I/home/libera/epics/base-3.14.12.2/include/os/Linux -I. -I/usr/local/qwt-6.0.1/include -I/home/libera/epics/base-3.14.12.2/include -I../src -I../../caQtDM_QtControls/src -I../moc ../src/caqtdm_lib.h -o ../moc/moc_caqtdm_lib.cpp
/usr/bin/moc-qt4 -DIO_OPTIMIZED_FOR_TABWIDGETS -DPYTHON -DEPICS -DQT_NO_DEBUG -DQT_PLUGIN -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtUiTools -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I/usr/include/python2.6 -I/home/libera/epics/base-3.14.12.2/include/os/Linux -I. -I/usr/local/qwt-6.0.1/include -I/home/libera/epics/base-3.14.12.2/include -I../src -I../../caQtDM_QtControls/src -I../moc ../src/mutexKnobData.h -o ../moc/moc_mutexKnobData.cpp
/usr/bin/moc-qt4 -DIO_OPTIMIZED_FOR_TABWIDGETS -DPYTHON -DEPICS -DQT_NO_DEBUG -DQT_PLUGIN -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtUiTools -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I/usr/include/python2.6 -I/home/libera/epics/base-3.14.12.2/include/os/Linux -I. -I/usr/local/qwt-6.0.1/include -I/home/libera/epics/base-3.14.12.2/include -I../src -I../../caQtDM_QtControls/src -I../moc ../src/MessageWindow.h -o ../moc/moc_MessageWindow.cpp
/usr/bin/moc-qt4 -DIO_OPTIMIZED_FOR_TABWIDGETS -DPYTHON -DEPICS -DQT_NO_DEBUG -DQT_PLUGIN -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtUiTools -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I/usr/include/python2.6 -I/home/libera/epics/base-3.14.12.2/include/os/Linux -I. -I/usr/local/qwt-6.0.1/include -I/home/libera/epics/base-3.14.12.2/include -I../src -I../../caQtDM_QtControls/src -I../moc ../src/limitsStripplotDialog.h -o ../moc/moc_limitsStripplotDialog.cpp
/usr/bin/moc-qt4 -DIO_OPTIMIZED_FOR_TABWIDGETS -DPYTHON -DEPICS -DQT_NO_DEBUG -DQT_PLUGIN -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtUiTools -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I/usr/include/python2.6 -I/home/libera/epics/base-3.14.12.2/include/os/Linux -I. -I/usr/local/qwt-6.0.1/include -I/home/libera/epics/base-3.14.12.2/include -I../src -I../../caQtDM_QtControls/src -I../moc ../src/limitsDialog.h -o ../moc/moc_limitsDialog.cpp
/usr/bin/moc-qt4 -DIO_OPTIMIZED_FOR_TABWIDGETS -DPYTHON -DEPICS -DQT_NO_DEBUG -DQT_PLUGIN -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtUiTools -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I/usr/include/python2.6 -I/home/libera/epics/base-3.14.12.2/include/os/Linux -I. -I/usr/local/qwt-6.0.1/include -I/home/libera/epics/base-3.14.12.2/include -I../src -I../../caQtDM_QtControls/src -I../moc ../src/limitsCartesianplotDialog.h -o ../moc/moc_limitsCartesianplotDialog.cpp
/usr/bin/moc-qt4 -DIO_OPTIMIZED_FOR_TABWIDGETS -DPYTHON -DEPICS -DQT_NO_DEBUG -DQT_PLUGIN -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtUiTools -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I/usr/include/python2.6 -I/home/libera/epics/base-3.14.12.2/include/os/Linux -I. -I/usr/local/qwt-6.0.1/include -I/home/libera/epics/base-3.14.12.2/include -I../src -I../../caQtDM_QtControls/src -I../moc ../src/sliderDialog.h -o ../moc/moc_sliderDialog.cpp
/usr/bin/moc-qt4 -DIO_OPTIMIZED_FOR_TABWIDGETS -DPYTHON -DEPICS -DQT_NO_DEBUG -DQT_PLUGIN -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtUiTools -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I/usr/include/python2.6 -I/home/libera/epics/base-3.14.12.2/include/os/Linux -I. -I/usr/local/qwt-6.0.1/include -I/home/libera/epics/base-3.14.12.2/include -I../src -I../../caQtDM_QtControls/src -I../moc ../src/processWindow.h -o ../moc/moc_processWindow.cpp
make[2]: *** [../obj1/caqtdm_lib.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/home/libera/epics/caqtdm-3.9.4/caQtDM_Lib/caQtDM_Lib1'
make[1]: *** [sub-caQtDM_Lib1-make_default] Error 2
make[1]: Leaving directory `/home/libera/epics/caqtdm-3.9.4/caQtDM_Lib'
make: *** [sub-caQtDM_Lib-make_default] Error 2

Could someone please advise?

**Comment by AntonMezger** [comment]
What Python version are you using? you may have to modify the python version defined in qtdefs.pri.

If you do not have python, you can disable it (also in qtdefs.pri)

**Comment by peterleban** [comment]
I'm using Pyhton2.6. Followed your suggestion to disable it in the qtprefs.pri and compiled OK. I have the app running well. Thanks!
